services:
  nexus:
    build: ./infraestructure/nexus
    container_name: "nexus3"
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    image: "nexus3-local:1.0.0"

  jenkins:
    build: ./infraestructure/jenkins
    container_name: "jenkins"
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    image: "jenkins-local:1.0.0"

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    read_only: false  # required to write to /tmp
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8082:8082"
    environment:
      - PROVIDER_OVERRIDE_STEPFUNCTIONS=v2
      - USE_LIGHT_IMAGE=0
      - DEBUG=1
      - PORT_WEB_UI=8082
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - START_WEB=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"  # required for some AWS services like AWS Lambda
    security_opt:
      - no-new-privileges:true

volumes:
  nexus-data:
    external: true
  jenkins-data:
    external: true