services:
  nexus:
    build: ./infraestructure/nexus
    container_name: "nexus3"
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    image: "nexus3-local:1.0.0"

volumes:
  nexus-data:
    external: true