services:
  nexus:
    build: ./infraestructure/nexus
    container_name: "nexus3"
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    image: "nexus3-local:1.0.0"

  jenkins:
    build: ./infraestructure/jenkins
    container_name: "jenkins"
    restart: always
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    image: "jenkins-local:1.0.0"

  local-stack:
    build: ./infraestructure/localstack
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./infraestructure/localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    image: "localstack:3.8"

volumes:
  nexus-data:
    external: true
  jenkins-data:
    external: true