pipeline {
    agent any

    options {
        timeout(time: 2, unit: 'MINUTES')
    }

    environment {
        IMAGE_NAME = "what-is-my-local-ip"
        DOCKER_REGISTRY = "http://localhost:8083/repository/docker-local/"
        DOCKER_CREDENTIALS = credentials('nexus-local')
        IMAGE_VERSION = "1.0.0"
    }

    stages {
        stage('Login to Nexus Docker Registry') {
            steps {
                script {
                    sh 'docker login -u $DOCKER_CREDENTIALS_USR -p $DOCKER_CREDENTIALS_PSW $DOCKER_REGISTRY'
                }
            }
        }

        stage ("build image") {
            steps {
                sh "docker build -f apps/ip_app/Dockerfile -t ${IMAGE_NAME} apps/ip_app/"
            }
        }
        stage ("Deply image") {
            steps {
                sh "docker tag ${IMAGE_NAME} ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}"
                sh "docker push ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION}"
            }
        }
    }
    post {
        always {
            // Clean images
            sh '''
            docker rmi ${IMAGE_NAME}:${IMAGE_VERSION} --force || true
            docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}:${IMAGE_VERSION} --force || true
            '''
        }
  }
}