pipeline {
    agent any

    options {
        timeout(time: 2, unit: 'MINUTES')
    }

    environment {
        IMAGE_NAME = "what-is-my-ip"
        DOCKER_REGISTRY = "localhost:8083"
        DOCKER_REPO = "docker-local"
        IMAGE_VERSION = "1.0.0"
    }

    stages {
        stage ("build image") {
            steps {
                sh "docker build -t ${IMAGE_NAME} ."
            }
        }

        stage ("Login in local registry") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'nexus-local', 
                                                 usernameVariable: 'NEXUS_USER', 
                                                 passwordVariable: 'NEXUS_PASS')]) {
                    script {
                        sh """
                            curl -u $NEXUS_USER:$NEXUS_PASS -X GET "$DOCKER_REGISTRY/service/rest/v1/repositories/$DOCKER_REPO"
                        """
                    }
                }
            }
        }
    }
}